---
# -------------------------------------------------------------------
# Install & manage Keycloak systemd service
# -------------------------------------------------------------------
- name: Ensure Keycloak database owner is correct
  community.postgresql.postgresql_owner:
    db: "{{ keycloak_db_name }}"
    new_owner: "{{ keycloak_db_user }}"
    login_host: "{{ keycloak_db_host }}"
    login_user: "{{ keycloak_db_user }}"
    login_password: "{{ keycloak_db_password }}"
    login_port: "{{ keycloak_db_port }}"
  when: keycloak_db_engine == "postgres"

- name: Install Keycloak systemd service
  ansible.builtin.template:
    src: keycloak.service.j2
    dest: /etc/systemd/system/keycloak.service
    owner: root
    group: root
    mode: "0644"
  register: keycloak_service_unit

- name: Reload systemd daemon if service file changed
  ansible.builtin.systemd:
    daemon_reload: true
  when: keycloak_service_unit.changed

- name: Enable and start Keycloak service
  ansible.builtin.systemd:
    name: keycloak
    enabled: true
    state: started
